management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: 'true'
  endpoint:
    metrics:
      enabled: 'true'
    prometheus:
      enabled: 'true'
    gateway:
      enabled: 'true'
spring:
  datasource:
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'
    password: postgres
    username: postgres
    url: 'jdbc:postgresql://localhost:5432/DigitalLibraryDB '
  application:
    name: ms-pedidos-gestion-productos
eureka:
  client:
    fetch-registry: 'true'
    serviceUrl:
      defaultZone: http://localhost:8889/eureka
server:
  port: '8081'
